### ISSUE TITLE
Funcionamiento del código nuevo: Comprobar | Testing of the new code

### ISSUE THREAD

**Issue by garridinsi** [scantnik/Scantnik2021#1]
Hay que probar el funcionamiento del nuevo código.
We have to test if the new code is working.

**Comment by Xabier41** [comment]
La conversión a Pascales está mal hecha // Conversion to Pascals is wrong

**Comment by garridinsi** [comment]
> La conversión a Pascales está mal hecha // Conversion to Pascals is wrong

Se ha resuelto con el nuevo commit? | Is the issue solved with the new commit? 1a82e9a

**Comment by garridinsi** [comment]
I've just added the code I think we need for the GPS. This new code needs testing.

Acabo de añadir el codigo nuevo que creo que es el que necesitamos para hacer funcionar el GPS. Hay que probarlo para asegurarnos de que funciona.
