### ISSUE TITLE
La conversión a Pascales está mal hecha // Conversion to Pascals is wrong

### ISSUE THREAD

**Issue by garridinsi** [scantnik/Scantnik2021#2]
La conversión a Pascales está mal hecha // Conversion to Pascals is wrong

_Originally posted by @Xabier41 in https://github.com/scantnik/Scantnik2021/issues/1#issuecomment-812009405_

**Comment by garridinsi** [comment]
Opened issue to do the tracking | Abierto nuevo problema para realizar seguimiento.

Puede ser que el problema se haya resuelto con el último commit: 1a82e9a
Is possible that the issue is closed with the new commit: 1a82e9a
No probado por mi parte | Not tested from my side

**Comment by RopeyOrc41** [comment]
Solucionado // Solved
