### ISSUE TITLE
Is not declared in this scope // No se declara en este ámbito

### ISSUE THREAD

**Issue by RopeyOrc41** [scantnik/Scantnik2021#3]
https://github.com/scantnik/Scantnik2021/blob/02a3d9966f8bb426ef8de35777d13d7922a0a16f/Scantnik_optimization/Scantnik_optimization.ino#L216

**Comment by RopeyOrc41** [comment]
Arduino:1.8.13 (Windows 10), Tarjeta:"Arduino Nano, ATmega328P"





















C:\Users\usuario\Documents\Arduino\Optimizaci_n_Scantnik\Optimizaci_n_Scantnik.ino: In function 'void loop()':

Optimizaci_n_Scantnik:179:5: error: 'gps_alt' was not declared in this scope

     gps_alt = gps.f_altitude();

     ^~~~~~~

Optimizaci_n_Scantnik:180:25: error: 'flat' was not declared in this scope

     gps.f_get_position(&flat, &flon, &age);

                         ^~~~

C:\Users\usuario\Documents\Arduino\Optimizaci_n_Scantnik\Optimizaci_n_Scantnik.ino:180:25: note: suggested alternative: 'float'

     gps.f_get_position(&flat, &flon, &age);

                         ^~~~

                         float

Optimizaci_n_Scantnik:180:32: error: 'flon' was not declared in this scope

     gps.f_get_position(&flat, &flon, &age);

                                ^~~~

C:\Users\usuario\Documents\Arduino\Optimizaci_n_Scantnik\Optimizaci_n_Scantnik.ino:180:32: note: suggested alternative: 'feof'

     gps.f_get_position(&flat, &flon, &age);

                                ^~~~

                                feof

Optimizaci_n_Scantnik:216:18: error: 'gps_alt' was not declared in this scope

   data += String(gps_alt);

                  ^~~~~~~

Optimizaci_n_Scantnik:218:18: error: 'flat' was not declared in this scope

   data += String(flat == TinyGPS::GPS_INVALID_F_ANGLE ? 0.0 : flat, 6);

                  ^~~~

C:\Users\usuario\Documents\Arduino\Optimizaci_n_Scantnik\Optimizaci_n_Scantnik.ino:218:18: note: suggested alternative: 'float'

   data += String(flat == TinyGPS::GPS_INVALID_F_ANGLE ? 0.0 : flat, 6);

                  ^~~~

                  float

Optimizaci_n_Scantnik:220:18: error: 'flon' was not declared in this scope

   data += String(flon == TinyGPS::GPS_INVALID_F_ANGLE ? 0.0 : flon, 6);

                  ^~~~

C:\Users\usuario\Documents\Arduino\Optimizaci_n_Scantnik\Optimizaci_n_Scantnik.ino:220:18: note: suggested alternative: 'feof'

   data += String(flon == TinyGPS::GPS_INVALID_F_ANGLE ? 0.0 : flon, 6);

                  ^~~~

                  feof

Optimizaci_n_Scantnik:224:17: error: expected primary-expression before '(' token

   data += String(gps.hdop() == TinyGPS::GPS_INVALID_HDOP ? 0 : gps.hdop();

                 ^

Optimizaci_n_Scantnik:224:74: error: expected ')' before ';' token

   data += String(gps.hdop() == TinyGPS::GPS_INVALID_HDOP ? 0 : gps.hdop();

                                                                          ^

Optimizaci_n_Scantnik:226:65: error: 'class TinyGPS' has no member named 'constellations'

   data += String(flat == TinyGPS::GPS_INVALID_F_ANGLE ? 0 : gps.constellations());

                                                                 ^~~~~~~~~~~~~~

exit status 1

'gps_alt' was not declared in this scope



Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by garridinsi** [comment]
The problem on compiling was that the flat, flon and gps_alt weren't declared as float.
Solved with the implementation on lines 60, 61 and 62. Solved with 02a3d99 commit

**Comment by garridinsi** [comment]
I'm reopening issue to do tracking
